name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:  # This should be under the `on` key, not on its own line

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Name
        run: echo "${{ toJson(github) }}"

      - name: Repo Name
        run: |
