name: GitHub Actions Demo
on:
  push:
    branches:
    - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
  jobs:
    name: Build
    runs-on: ubuntu-latest
    steps:
      name: Trigger Name
      run: echo "The event that triggered this workflow is: ${{ github.event_name }}"
      name: Repo Name
      run: |
          # Extract branch name from github.ref
          branch_name=${{ github.ref }}
          if [[ $branch_name == refs/heads/* ]]; then
            branch_name=${branch_name#refs/heads/}
          fi
          echo "The current branch is: $branch_name"
      name: List all files in the repository
      run: |
          echo "Listing all files in the repository:"
          ls -R
      
    
      
